README
======

FrenchPress is a Java EE-based blogging system. It is intended to be a simple, yet non-trivial example of how one can
build Java EE applications, using a variety of the technologies available in the platform.

Building
--------

FrenchPress uses http://gradle.org[Gradle] to build. To build the deployable archive, execute:

[source,bash]
----
$ gradle assemble
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:war
:assemble

BUILD SUCCESSFUL

Total time: 7.958 secs
-----

Testing
-------
Unit tests can be run with via the `test` task, though most of the tests are integration tests, which are run via
http://arquillian.org[Arquillian]. The currently supported configurations are as follows:

[options="header"]
|====================
| Container | Mode | Task Name | Notes
| GlassFish 4 | Managed | glassfishManagedTest | Servers is expected to be in `glassfish4` in the projects' root directory
| | Embedded  | glassfishEmbeddedTest |
| | Remote  | glassfishRemoteTest | Build currenly assumes an unsecured server with the default port configuration
| JBoss AS 7 | Managed | jbossManagedTest |
|====================

Example
~~~~~~~

[source,bash]
-----
$ gradle --daemon glassfishEmbeddedTest
:compileJava
:processResources
:classes
:compileTestJava
:processTestResources
:testClasses
:glassfishEmbeddedTest

BUILD SUCCESSFUL

Total time: 29.774 secs
-----

To assist in setting up a test environment, you can use a script called `frenchpress.sh`. You can get help from the script
via the `-?` command line parameter.
